import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import { useAuth } from "./_core/hooks/useAuth";
import { startLogin } from "./const";
import Home from "./pages/Home";
import NotFound from "./pages/NotFound";
import AnimeDetails from "./pages/AnimeDetails";
import Watch from "./pages/Watch";
import LibraryPage from "./pages/Library";
import Browse from "./pages/Browse";
import { Route, Switch, Link, useLocation } from "wouter";
import { Compass, History, Home as HomeIcon, Library, Menu, Search, Tags, Tv, X } from "lucide-react";
import { useState } from "react";

function Shell({ children }: { children: React.ReactNode }) {
  const [location] = useLocation(); const [open, setOpen] = useState(false); const { user, logout } = useAuth();
  const nav = [{ href: "/", label: "Home", icon: HomeIcon }, { href: "/explore", label: "Explore", icon: Compass }, { href: "/genres", label: "Genres", icon: Tags }, { href: "/schedule", label: "Schedule", icon: Tv }, { href: "/history", label: "History", icon: History }, { href: "/watchlist", label: "Watchlist", icon: Library }];
  return <div className="min-h-screen bg-[#090b12] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#090b12]/85 backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-[1440px] items-center gap-5 px-4 lg:px-8"><button className="rounded-lg p-1 lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X size={20} /> : <Menu size={20} />}</button><Link href="/" className="text-xl font-black tracking-tight">ani<span className="text-[#a5f3fc]">daku</span></Link><nav className="hidden items-center gap-1 lg:flex">{nav.slice(0, 4).map(({ href, label }) => <Link key={href} href={href} className={`rounded-lg px-3 py-2 text-sm font-medium hover:bg-white/10 ${location === href ? "text-[#a5f3fc]" : "text-white/65"}`}>{label}</Link>)}</nav><div className="ml-auto flex items-center gap-2"><Link href="/search" className="flex h-9 items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 text-sm text-white/55 hover:text-white"><Search size={16} /><span className="hidden sm:inline">Search anime</span></Link>{user ? <button onClick={() => void logout()} className="hidden rounded-xl bg-white/10 px-3 py-2 text-sm font-semibold hover:bg-white/15 md:block">Log out</button> : <button onClick={() => startLogin()} className="hidden rounded-xl bg-white/10 px-3 py-2 text-sm font-semibold hover:bg-white/15 md:block">Sign in</button>}</div></div>{open && <nav className="border-t border-white/10 bg-[#0e111b] p-3 lg:hidden">{[...nav, { href: "/search", label: "Search", icon: Search }].map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-xl px-4 py-3 text-white/70 hover:bg-white/10">{Icon && <Icon size={18} />}{label}</Link>)}</nav>}</header><main>{children}</main><nav className="fixed inset-x-3 bottom-3 z-40 flex justify-around rounded-2xl border border-white/10 bg-[#111522]/95 p-2 shadow-2xl backdrop-blur-xl lg:hidden">{nav.slice(0, 5).map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex flex-col items-center gap-1 rounded-xl px-3 py-1.5 text-[10px] ${location === href ? "text-[#a5f3fc]" : "text-white/45"}`}>{Icon && <Icon size={17} />}{label}</Link>)}</nav></div>;
}
function Router() { return <Shell><Switch><Route path="/" component={Home} /><Route path="/explore" component={() => <Browse mode="explore" />} /><Route path="/search" component={() => <Browse mode="search" />} /><Route path="/trending" component={() => <Browse mode="trending" />} /><Route path="/popular" component={() => <Browse mode="popular" />} /><Route path="/latest" component={() => <Browse mode="latest" />} /><Route path="/upcoming" component={() => <Browse mode="upcoming" />} /><Route path="/genres" component={() => <Browse mode="genre" />} /><Route path="/genre/:genre" component={() => <Browse mode="genre" />} /><Route path="/anime/:id" component={AnimeDetails} /><Route path="/schedule" component={LibraryPage} /><Route path="/history" component={LibraryPage} /><Route path="/watchlist" component={LibraryPage} /><Route path="/watch/:id/:episode" component={Watch} /><Route component={NotFound} /></Switch></Shell>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="dark"><TooltipProvider><Toaster /><Router /></TooltipProvider></ThemeProvider></ErrorBoundary>; }
