import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Play, Plus, Search, Star } from "lucide-react";
import { getCollection, imageOf, recall, remember, searchAnime, titleOf, type Anime } from "@/lib/anilist";
import { toast } from "sonner";
import LoadingState from "@/components/LoadingState";

const genres = ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Horror", "Mystery", "Romance", "Sci-Fi", "Sports", "Thriller", "Music"];
const copy: Record<string, { eyebrow: string; title: string; description: string; kind: "trending" | "popular" | "latest" | "upcoming" | "genre" }> = {
  trending: { eyebrow: "Live pulse", title: "Trending now", description: "The titles anime fans are watching and talking about right now.", kind: "trending" },
  popular: { eyebrow: "All-time favorites", title: "Popular anime", description: "A reliable starting point, ranked by AniList popularity.", kind: "popular" },
  latest: { eyebrow: "Fresh updates", title: "Latest episodes", description: "Recently updated series, pulled from the catalog in real time.", kind: "latest" },
  upcoming: { eyebrow: "On the horizon", title: "Upcoming anime", description: "Announced titles and unreleased series worth keeping an eye on.", kind: "upcoming" },
};

function Card({ anime, rank }: { anime: Anime; rank?: number }) {
  const [saved, setSaved] = useState(() => recall<number[]>("watchlist", []).includes(anime.id));
  const toggle = () => { const list = recall<number[]>("watchlist", []); const next = saved ? list.filter((id) => id !== anime.id) : [...list, anime.id]; remember("watchlist", next); setSaved(!saved); toast(saved ? "Removed from watchlist" : "Added to watchlist"); };
  return <article className="group relative min-w-0"><Link href={`/anime/${anime.id}`} className="block"><div className="relative aspect-[2/3] overflow-hidden rounded-xl bg-white/5"><img src={imageOf(anime)} alt={titleOf(anime)} loading="lazy" className="h-full w-full object-cover transition duration-300 group-hover:scale-105 group-hover:brightness-75" />{rank && <span className="absolute left-2 top-2 grid h-7 w-7 place-items-center rounded-lg bg-[#a5f3fc] text-xs font-black text-[#08111d]">{rank}</span>}<span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-[10px] font-bold">{anime.format || "TV"}</span><div className="absolute inset-0 grid place-items-center opacity-0 transition group-hover:opacity-100"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#a5f3fc] text-[#07131d]"><Play size={16} fill="currentColor" /></span></div></div></Link><button onClick={toggle} aria-label={saved ? "Remove from watchlist" : "Add to watchlist"} className={`absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-lg backdrop-blur ${saved ? "bg-[#a5f3fc] text-[#08111d]" : "bg-black/45 text-white hover:bg-white/20"}`}>{saved ? <Check size={14} /> : <Plus size={14} />}</button><Link href={`/anime/${anime.id}`} className="mt-2 block truncate text-sm font-semibold hover:text-[#a5f3fc]">{titleOf(anime)}</Link><div className="mt-1 flex items-center gap-2 text-[11px] text-white/45"><span>{anime.seasonYear || "—"}</span><span>•</span><span className="flex items-center gap-1 text-[#fbbf24]"><Star size={11} fill="currentColor" />{anime.averageScore ? (anime.averageScore / 10).toFixed(1) : "—"}</span></div></article>;
}

export default function Browse({ mode = "explore" }: { mode?: string }) {
  const [location, navigate] = useLocation();
  const [query, setQuery] = useState(() => new URLSearchParams(window.location.search).get("q") || "");
  const [urlGenre, setUrlGenre] = useState(() => new URLSearchParams(window.location.search).get("genre") || "");
  useEffect(() => { const syncUrl = () => { const params = new URLSearchParams(window.location.search); setQuery(params.get("q") || ""); setUrlGenre(params.get("genre") || ""); }; window.addEventListener("popstate", syncUrl); syncUrl(); return () => window.removeEventListener("popstate", syncUrl); }, []);
  const genre = urlGenre || (mode === "genre" ? location.split("/").pop() : "");
  const config = mode === "genre" ? { eyebrow: "Browse by genre", title: genre || "Genre", description: `Explore ${genre || "anime"} titles from AniList.`, kind: "genre" as const } : copy[mode] || { eyebrow: "The catalog", title: "Explore anime", description: "Search, filter, and find something new to watch.", kind: "popular" as const };
  const [items, setItems] = useState<Anime[]>([]); const [page, setPage] = useState(1); const [hasNext, setHasNext] = useState(false); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(query);
  useEffect(() => { setSearch(query); setPage(1); setItems([]); setHasNext(false); }, [query, genre, mode]);
  useEffect(() => { if (mode !== "search" && mode !== "explore") return; const value = search.trim(); if (value === query) return; const timer = window.setTimeout(() => { const nextUrl = `/search${value ? `?q=${encodeURIComponent(value)}` : ""}`; window.history.pushState({}, "", nextUrl); setQuery(value); navigate(nextUrl); }, 400); return () => window.clearTimeout(timer); }, [search, query, mode, navigate]);
  useEffect(() => { setLoading(true); const load = query ? searchAnime(query, page, genre || undefined) : getCollection(config.kind, page, genre || undefined); load.then((result) => { setItems((current) => page === 1 ? result.items : [...current, ...result.items]); setHasNext(result.pageInfo.hasNextPage); }).catch(() => toast.error("Could not load this catalog")).finally(() => setLoading(false)); }, [query, genre, page, config.kind]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); const value = search.trim(); const nextUrl = `/search${value ? `?q=${encodeURIComponent(value)}` : ""}`; window.history.pushState({}, "", nextUrl); setQuery(value); navigate(nextUrl); };
  return <div className="mx-auto max-w-[1440px] px-4 py-8 pb-28 sm:py-10 lg:px-8 lg:pb-12"><div className="flex flex-col gap-6 border-b border-white/10 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a5f3fc]">{query ? "Search results" : config.eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">{query ? `Results for “${query}”` : config.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/50">{config.description}</p></div><form onSubmit={submit} className="search-form flex w-full max-w-md items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2"><Search size={17} className="text-white/35" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search anime..." className="search-field min-w-0 flex-1 bg-transparent text-sm placeholder:text-white/30" /><button type="submit" className="rounded-lg bg-[#a5f3fc] px-3 py-1.5 text-xs font-black text-[#07131d]">Search</button></form></div>{mode === "explore" && <div className="mt-6 flex gap-2 overflow-x-auto pb-1 scrollbar-none">{["trending", "popular", "latest", "upcoming"].map((item) => <Link key={item} href={`/${item}`} className="whitespace-nowrap rounded-full border border-white/10 px-4 py-2 text-xs font-bold capitalize text-white/60 hover:border-[#a5f3fc]/50 hover:text-[#a5f3fc]">{item}</Link>)}</div>}{mode === "genre" && <div className="mt-6 flex flex-wrap gap-2">{genres.map((item) => <Link key={item} href={`/genre/${item.toLowerCase()}`} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${item.toLowerCase() === genre?.toLowerCase() ? "border-[#a5f3fc] bg-[#a5f3fc] text-[#07131d]" : "border-white/10 text-white/55 hover:border-white/30"}`}>{item}</Link>)}</div>}{loading && page === 1 ? <div className="py-20 text-center text-white/45"><LoadingState label="Loading anime data" /></div> : items.length ? <><div className="mt-8 grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-4 lg:grid-cols-6">{items.map((anime, i) => <Card key={`${anime.id}-${i}`} anime={anime} rank={!query && page === 1 && config.kind === "trending" ? i + 1 : undefined} />)}</div>{hasNext && <div className="mt-10 flex justify-center"><button disabled={loading} onClick={() => setPage((current) => current + 1)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-5 py-3 text-sm font-bold hover:border-[#a5f3fc]/50 disabled:opacity-50">{loading ? "Loading..." : "Load more"}<ArrowRight size={15} /></button></div>}</> : <div className="py-20 text-center text-white/45"><p>No anime matched this request.</p><Link href="/explore" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#a5f3fc]">Back to explore <ChevronRight size={15} /></Link></div>}</div>;
}
