import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { CalendarDays, Check, Clock3, Library as LibraryIcon, Play, Trash2 } from "lucide-react";
import { getAnime, getSchedule, imageOf, titleOf, type Anime, recall, remember } from "@/lib/anilist";

const genres = ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Romance", "Sci-Fi", "Thriller", "Mystery", "Sports", "Slice of Life", "Supernatural", "Historical", "Horror", "Music"];
export default function Library() { const [location] = useLocation(); const kind = location.slice(1) || "watchlist"; const [items, setItems] = useState<Anime[]>([]); const [schedule, setSchedule] = useState<Anime[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (kind === "schedule") { getSchedule().then(setSchedule).finally(() => setLoading(false)); return; } const ids = kind === "history" ? Object.keys(recall<Record<string, number>>("progress", {})).map((key) => Number(key.split(":")[0])) : recall<number[]>("watchlist", []); Promise.all(Array.from(new Set(ids)).slice(0, 18).map((id) => getAnime(id))).then((data) => setItems(data.filter(Boolean) as Anime[])).finally(() => setLoading(false)); }, [kind]);
  if (kind === "genres") return <div className="mx-auto max-w-6xl px-4 py-12 pb-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a5f3fc]">Browse by mood</p><h1 className="mt-2 text-4xl font-black">Genres</h1><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{genres.map((genre, i) => <Link key={genre} href={`/genre/${genre.toLowerCase()}`} className="group rounded-xl border border-white/10 bg-gradient-to-br from-[#131a2d] to-[#11131e] p-4 hover:border-[#a5f3fc]/50"><span className="text-xs font-black text-white/20">{String(i + 1).padStart(2, "0")}</span><p className="mt-8 font-bold group-hover:text-[#a5f3fc]">{genre}</p></Link>)}</div></div>;
  if (kind === "schedule") return <div className="mx-auto max-w-6xl px-4 py-12 pb-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a5f3fc]">Release radar</p><h1 className="mt-2 text-4xl font-black">Weekly schedule</h1>{loading ? <div className="py-20 text-center text-white/45">Loading airing updates...</div> : schedule.length ? <div className="mt-8 grid gap-3 md:grid-cols-2">{schedule.map((anime) => <div key={anime.id} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/[.03] p-3"><img src={imageOf(anime)} alt="" className="h-16 w-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><Link href={`/anime/${anime.id}`} className="truncate font-bold hover:text-[#a5f3fc]">{titleOf(anime)}</Link><p className="mt-1 text-xs text-white/45">Episode {anime.nextAiringEpisode?.episode} · {anime.nextAiringEpisode ? new Date(anime.nextAiringEpisode.airingAt * 1000).toLocaleString([], { weekday: "long", hour: "numeric", minute: "2-digit" }) : "Time unavailable"}</p></div><Link href={`/watch/${anime.id}/${anime.nextAiringEpisode?.episode || 1}`} className="rounded-lg bg-white/10 p-2 hover:bg-[#a5f3fc] hover:text-[#07131d]" aria-label="Watch episode"><Play size={15} fill="currentColor" /></Link></div>)}</div> : <div className="py-20 text-center text-white/45">No airing times are available right now.</div>}</div>;
  return <div className="mx-auto max-w-6xl px-4 py-12 pb-24"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a5f3fc]">Your library</p><h1 className="mt-2 text-4xl font-black">{kind === "history" ? "Continue watching" : "Watchlist"}</h1></div>{items.length > 0 && <button onClick={() => { if (kind === "history") remember("progress", {}); else remember("watchlist", []); setItems([]); }} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-white/60 hover:bg-white/10"><Trash2 size={15} /> Clear all</button>}</div>{loading ? <div className="py-20 text-center text-white/45">Loading your library...</div> : items.length ? <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-6">{items.map((anime) => <Link key={anime.id} href={`/anime/${anime.id}`} className="group"><div className="relative overflow-hidden rounded-xl"><img src={imageOf(anime)} alt={titleOf(anime)} className="aspect-[2/3] w-full object-cover transition group-hover:scale-105" /><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-[10px] font-bold">{kind === "history" ? <><Clock3 size={10} className="mr-1 inline" /> Resume</> : <><Check size={10} className="mr-1 inline" /> Saved</>}</span></div><p className="mt-2 truncate text-sm font-semibold">{titleOf(anime)}</p></Link>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-white/15 py-16 text-center"><LibraryIcon className="mx-auto text-white/25" size={34} /><h2 className="mt-4 text-xl font-bold">Nothing here yet</h2><p className="mt-2 text-sm text-white/45">Save anime from browse or detail pages and it will appear here.</p><Link href="/explore" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#a5f3fc] px-4 py-2.5 text-sm font-bold text-[#07131d]"><Play size={15} /> Explore anime</Link></div>}</div>;
}
