'use client'

import { useEffect, useState } from 'react'
import { Search, Play, Plus, ChevronRight, Menu, X, Star, ShieldCheck, ExternalLink } from 'lucide-react'

type Anime = { id:number; title:{romaji:string; english?:string}; coverImage:{extraLarge:string; color?:string}; bannerImage?:string; description?:string; episodes?:number; duration?:number; averageScore?:number; genres:string[]; status?:string; seasonYear?:number }
const fallback: Anime[] = [
 {id:1,title:{romaji:'Solo Leveling',english:'Solo Leveling'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx204725-7kB5xK1fZqQ5.jpg'},bannerImage:'https://s4.anilist.co/file/anilistcdn/media/anime/banner/204725-7ZKqPzKx.jpg',description:'They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter.',episodes:25,averageScore:87,genres:['Action','Adventure','Fantasy'],status:'FINISHED',seasonYear:2024},
 {id:2,title:{romaji:'The Apothecary Diaries',english:'The Apothecary Diaries'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx161645-7nqW8R9sQ1wL.png'},episodes:48,averageScore:88,genres:['Drama','Mystery','Historical'],status:'RELEASING',seasonYear:2025},
 {id:3,title:{romaji:'One Piece'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-Gtlz7J8H9q.jpg'},episodes:1150,averageScore:87,genres:['Action','Adventure','Fantasy'],status:'RELEASING'},
 {id:4,title:{romaji:'Dandadan'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx184660-QxY2T4bA.jpg'},episodes:24,averageScore:86,genres:['Action','Comedy','Supernatural'],status:'RELEASING',seasonYear:2025},
 {id:5,title:{romaji:'Jujutsu Kaisen'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-y9XvP2mL.jpg'},episodes:47,averageScore:87,genres:['Action','Supernatural'],status:'FINISHED',seasonYear:2023},
 {id:6,title:{romaji:'Demon Slayer'},coverImage:{extraLarge:'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-FsRkC4aB.jpg'},episodes:55,averageScore:84,genres:['Action','Fantasy'],status:'FINISHED'}
]
const providers = [{name:'MegaPlay', detail:'Primary server', url:'https://megaplay.buzz/api'}, {name:'VidNest', detail:'AnimePahe server', url:'https://vidnest.fun'}, {name:'ZokoAnime', detail:'Backup server', url:'https://zokoanime.video'}]

export default function Home() { const [anime,setAnime]=useState<Anime[]>(fallback); const [query,setQuery]=useState(''); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Anime|null>(null); const [provider,setProvider]=useState(providers[0]); const [menu,setMenu]=useState(false); const [loading,setLoading]=useState(false)
 useEffect(()=>{ let active=true; setLoading(true); fetch(`/api/anilist${search?`?search=${encodeURIComponent(search)}`:''}`).then(r=>r.json()).then(d=>{if(active&&d.media?.length)setAnime(d.media)}).catch(()=>{}).finally(()=>active&&setLoading(false)); return()=>{active=false} },[search])
 const submit=(e:React.FormEvent)=>{e.preventDefault();setSearch(query)}
 return <main>
  <header className="topbar"><div className="nav-inner"><button className="icon-btn mobile-only" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button><a className="brand" href="#top"><span className="brand-mark">A</span><span>anidaku</span></a><nav className={menu?'nav-links open':'nav-links'}><a className="active" href="#home">Home</a><a href="#trending">Trending</a><a href="#genres">Genres</a><a href="#schedule">Schedule</a></nav><form className="search" onSubmit={submit}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anime..." aria-label="Search anime"/><kbd>⌘ K</kbd></form><button className="profile">Guest</button></div></header>
  <section id="home" className="hero"><div className="hero-glow"/><div className="hero-content"><div className="eyebrow"><span className="pulse"/> #1 TRENDING THIS WEEK</div><h1>Solo Leveling</h1><p className="hero-sub"><b>2 Seasons</b><span>•</span><b>25 Episodes</b><span>•</span><span className="rating"><Star/> 8.7</span></p><p className="hero-copy">They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter. After a life-changing awakening, Sung Jinwoo is ready to level up.</p><div className="hero-actions"><button className="primary" onClick={()=>setSelected(anime[0])}><Play fill="currentColor"/> Watch now</button><button className="secondary" onClick={()=>setSelected(anime[0])}><Plus/> Add to list</button></div></div><div className="hero-art"><div className="art-card"><img src={fallback[0].coverImage.extraLarge} alt="Solo Leveling key art"/><div className="art-shade"/></div></div></section>
  <div className="page-wrap"><section id="trending" className="section"><div className="section-head"><div><span className="section-kicker">Discover</span><h2>Trending now</h2></div><a href="#all">View all <ChevronRight/></a></div><div className="anime-grid">{anime.slice(0,6).map((item,i)=><AnimeCard key={item.id} item={item} index={i} onClick={()=>setSelected(item)}/>)}</div></section><section className="split-sections"><div className="mini-section" id="schedule"><div className="section-head"><div><span className="section-kicker">Updated daily</span><h2>Continue watching</h2></div></div><div className="continue-card" onClick={()=>setSelected(anime[0])}><img src={anime[0].coverImage.extraLarge} alt=""/><div><span className="progress-label">Episode 7 of 13</span><h3>Solo Leveling</h3><div className="progress"><i/></div><small>12:45 remaining</small></div><Play className="continue-play"/></div></div><div className="mini-section" id="genres"><div className="section-head"><div><span className="section-kicker">Browse by mood</span><h2>Popular genres</h2></div></div><div className="genre-grid">{['Action','Adventure','Comedy','Drama','Fantasy','Mystery','Romance','Sci-Fi'].map(g=><button key={g} onClick={()=>{setQuery(g);setSearch(g)}}>{g}<ChevronRight/></button>)}</div></div></section><section className="trust"><ShieldCheck/><div><strong>Curated for anime fans</strong><span>Anidaku filters out adult content and keeps your watchlist safe.</span></div><span className="trust-tag">No hentai</span></section></div>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="watch-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><div className="watch-head"><div><span className="section-kicker">Now streaming</span><h2>{selected.title.english||selected.title.romaji}</h2><p>{selected.genres?.slice(0,3).join('  •  ')}</p></div><div className="provider-tabs">{providers.map(p=><button className={provider.name===p.name?'selected':''} key={p.name} onClick={()=>setProvider(p)}>{p.name}</button>)}</div></div><div className="video-frame"><div className="video-placeholder"><Play fill="currentColor"/><strong>Ready to watch</strong><span>Choose a server below to start streaming</span><a href={provider.url} target="_blank" rel="noreferrer">Open {provider.name} <ExternalLink/></a></div></div><div className="server-note"><span className="online-dot"/> {provider.name} · {provider.detail}<span className="server-url">{provider.url}</span></div></div></div>}
 </main> }
function AnimeCard({item,index,onClick}:{item:Anime;index:number;onClick:()=>void}) { return <button className="anime-card" onClick={onClick}><div className="poster"><img src={item.coverImage.extraLarge} alt={`${item.title.english||item.title.romaji} poster`}/><span className="card-rank">0{index+1}</span><span className="play-overlay"><Play fill="currentColor"/></span></div><div className="card-meta"><h3>{item.title.english||item.title.romaji}</h3><p><span>{item.status==='RELEASING'?'TV':'TV'}</span><span>•</span><span>{item.episodes||'?'} eps</span><span>•</span><span className="score"><Star/> {((item.averageScore||0)/10).toFixed(1)}</span></p></div></button> }
